version: '3'

services:
  mongo:
    image: bitnami/mongodb
    environment:
      MONGODB_ROOT_USERNAME: test
      MONGODB_ROOT_PASSWORD: test
    volumes:
      - mongodb:/bitnami/mongodb
    ports: 
      - 27017:27017

  bot:
    image: ${IMAGE_URI}
    restart: on-failure
    volumes:
      - ./logs:/app/logs
    # command: ["python", "server.py"]
    depends_on:
      - mongo
    links:
      - mongo

volumes:
  mongodb: