version: '3'

services:
  fix-mongodb-permissions:
    image: bitnami/mongodb
    user: root
    command: chown -R 1001:1001 /bitnami
    volumes:
      - ./mongodata:/bitnami/mongodb

  mongo:
    container_name: mongodb
    image: bitnami/mongodb
    environment:
      MONGODB_ROOT_USERNAME: $MONGO_ROOT_USERNAME
      MONGODB_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD
    env_file:
      - .env
    volumes:
      - ./mongodata:/bitnami/mongodb
    ports: 
      - 27017:27017

  bot:
    image: ${IMAGE_URI}
    restart: on-failure
    volumes:
      - ./logs:/app/logs
    command: ["python", "server.py"]
    env_file: 
      - .env
    depends_on:
      - mongo
    links:
      - mongo
