version: '3.3'

services:
  mongo:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    env_file:
      - .env
    volumes:
      - mongodb:/data/db
    ports: 
      - 27017:27017

  bot:
    container_name: recipes-bot
    build: ./
    restart: on-failure
    env_file: 
      - .env
    volumes:
      - ./logs:/app/logs
    security_opt:
      - no-new-privileges:true
    command: ["python", "server.py"]
    depends_on:
      - mongo

volumes:
  mongodb: