version: '3'

services:
  mongo:
    container_name: mongodb
    image: bitnami/mongodb
    environment:
      MONGODB_ROOT_USERNAME: $MONGO_ROOT_USERNAME
      MONGODB_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD
    env_file:
      - .env
    volumes:
      - ./mongodata:/bitnami/mongodb
    ports: 
      - 27017:27017

  bot:
    image: ${IMAGE_URI}
    restart: on-failure
    volumes:
      - ./logs:/app/logs
    command: ["python", "server.py", "-e", "webhook"]
    env_file: 
      - .env
    ports:
      - 8443:3001
    depends_on:
      - mongo
    links:
      - mongo
