version: '3'

services:
  mongo:
    image: bitnami/mongodb
    environment:
      MONGODB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGODB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb:/bitnami/mongodb
    ports: 
      - 27017:27017

  bot:
    image: ${IMAGE_URI}
    restart: on-failure
    volumes:
      - ./logs:/app/logs
    command: ["python", "server.py"]
    env_file: 
      - .env
    depends_on:
      - mongo
    links:
      - mongo

volumes:
  mongodb: