version: '3'

services:
  mongo:
    container_name: mongodb
    image: bitnami/mongodb
    environment:
      MONGODB_ROOT_USERNAME: $MONGO_USER
      MONGODB_ROOT_PASSWORD: $MONGO_PASSWORD
    env_file:
      - .env
    volumes:
      - mongodb:/bitnami/mongodb
    ports: 
      - 27017:27017

  bot:
    container_name: recipes-bot
    # build: ./
    image: ${AWS_ECR_IMAGE}:latest
    restart: on-failure
    env_file: 
      - .env
    volumes:
      - ./logs:/app/logs
    command: ["python", "server.py"]
    depends_on:
      - mongo
    links:
      - mongo

volumes:
  mongodb: