version: '3.3'

services:
    mongo:
        image: mongo
        container_name: mongodb
        environment:
          - MONGO_INITDB_ROOT_USERNAME=root
          - MONGO_INITDB_ROOT_PASSWORD=example
        ports: 
          - 27017:27017